sem_cubo = {
    "INT" : {
        "INT" : {
            "+" : "INT",
            "-" : "INT",
            "*" : "INT",
            "/" : "INT",
            "%" : "INT",
            ">" : "BOOL",
            ">=" : "BOOL",
            "<" : "BOOL",
            "<=" : "BOOL",
            "=" : "INT",
            "==" : "BOOL",
            "!=" : "BOOL",
            "AND" : "error",
            "OR" : "error"
        },
        "FLOAT" : {
            "+" : "error",
            "-" : "error",
            "*" : "error",
            "/" : "error",
            "%" : "error",
            ">" : "BOOL",
            ">=" : "BOOL",
            "<" : "BOOL",
            "<=" : "BOOL",
            "=" : "error",
            "==" : "BOOL",
            "!=" : "BOOL",
            "AND" : "error",
            "OR" : "error"
        },
        "BOOL" : {
            "+" : "error",
            "-" : "error",
            "*" : "error",
            "/" : "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
        },
        "CHAR": {
            "+": "error",
            "-": "error",
            "*": "error",
            "/": "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
        },
        "DATASET": {
            "+": "error",
            "-": "error",
            "*": "error",
            "/": "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
    }
    },
    "FLOAT" : {
        "INT" : {
            "+" : "error",
            "-" : "error",
            "*" : "error",
            "/" : "error",
            "%" : "error",
            ">" : "BOOL",
            ">=" : "BOOL",
            "<" : "BOOL",
            "<=" : "BOOL",
            "=" : "error",
            "==" : "BOOL",
            "!=" : "BOOL",
            "AND" : "error",
            "OR" : "error"
        
        },
        "FLOAT" : {
            "+" : "FLOAT",
            "-" : "FLOAT",
            "*" : "FLOAT",
            "/" : "FLOAT",
            "%" : "error",
            ">" : "BOOL",
            ">=" : "BOOL",
            "<" : "BOOL",
            "<=" : "BOOL",
            "=" : "FLOAT",
            "==" : "BOOL",
            "!=" : "BOOL",
            "AND" : "error",
            "OR" : "error"
        },
        "BOOL" : {
            "+" : "error",
            "-" : "error",
            "*" : "error",
            "/" : "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
        },
        "CHAR": {
            "+": "error",
            "-": "error",
            "*": "error",
            "/": "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
        },
        "DATASET": {
            "+": "error",
            "-": "error",
            "*": "error",
            "/": "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
}
},
    "BOOL" : {
        "INT" : {
            "+" : "error",
            "-" : "error",
            "*" : "error",
            "/" : "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
        },
        "FLOAT" : {
            "+" : "error",
            "-" : "error",
            "*" : "error",
            "/" : "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
        },
        "BOOL" : {
            "+" : "error",
            "-" : "error",
            "*" : "error",
            "/" : "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "BOOL",
            "==" : "BOOL",
            "!=" : "BOOL",
            "AND" : "BOOL",
            "OR" : "BOOL"
        },
        "CHAR": {
            "+" : "error",
            "-" : "error",
            "*" : "error",
            "/" : "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
        },
        "DATASET": {
            "+": "error",
            "-": "error",
            "*": "error",
            "/": "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
    }
    },
    "CHAR": {
        "INT": {
            "+" : "error",
            "-" : "error",
            "*" : "error",
            "/" : "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
        },
        "FLOAT": {
            "+" : "error",
            "-" : "error",
            "*" : "error",
            "/" : "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
        },
        "BOOL": {
            "+" : "error",
            "-" : "error",
            "*" : "error",
            "/" : "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
        },
        "CHAR": {
            "+": "CHAR",
            "-": "error",
            "*": "error",
            "/": "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "CHAR",
            "==" : "BOOL",
            "!=" : "BOOL",
            "AND" : "error",
            "OR" : "error"
        },
        "DATASET": {
            "+": "error",
            "-": "error",
            "*": "error",
            "/": "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
    }
    },
    "DATASET": {
        "INT": {
            "+" : "error",
            "-" : "error",
            "*" : "error",
            "/" : "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
        },
        "FLOAT": {
            "+" : "error",
            "-" : "error",
            "*" : "error",
            "/" : "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
        },
        "BOOL": {
            "+" : "error",
            "-" : "error",
            "*" : "error",
            "/" : "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
        },
        "CHAR": {
            "+": "error",
            "-": "error",
            "*": "error",
            "/": "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "DATASET",
            "==" : "BOOL",
            "!=" : "BOOL",
            "AND" : "error",
            "OR" : "error"
        },
        "DATASET": {
            "+": "error",
            "-": "error",
            "*": "error",
            "/": "error",
            "%" : "error",
            ">" : "error",
            ">=" : "error",
            "<" : "error",
            "<=" : "error",
            "=" : "error",
            "==" : "error",
            "!=" : "error",
            "AND" : "error",
            "OR" : "error"
    }
            }
}

